### ISSUE TITLE
Jooh's fork error

### ISSUE THREAD

**Issue by egarza** [cbedetti/Dcm2Bids#10]
Hi, tried to run yours, jooh, but I get this error:

```
Traceback (most recent call last):
  File "/home/egarza/MRI/apps/Dcm2Bids/scripts/dcm2bids", line 93, in <module>
    sys.exit(main())
  File "/home/egarza/MRI/apps/Dcm2Bids/scripts/dcm2bids", line 88, in main
    app = Dcm2bids(**vars(args))
  File "/home/egarza/MRI/apps/Dcm2Bids/dcm2bids/dcm2bids.py", line 29, in __init__
    self.dicomdir = os.path.join(outputdir,'tmp_dcm2bids')
  File "/usr/local/bin/miniconda/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "/home/egarza/MRI/apps/Dcm2Bids/scripts/dcm2bids", line 93, in <module>
    sys.exit(main())
  File "/home/egarza/MRI/apps/Dcm2Bids/scripts/dcm2bids", line 88, in main
    app = Dcm2bids(**vars(args))
  File "/home/egarza/MRI/apps/Dcm2Bids/dcm2bids/dcm2bids.py", line 29, in __init__
    self.dicomdir = os.path.join(outputdir,'tmp_dcm2bids')
  File "/usr/local/bin/miniconda/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "/home/egarza/MRI/apps/Dcm2Bids/scripts/dcm2bids", line 93, in <module>
    sys.exit(main())
  File "/home/egarza/MRI/apps/Dcm2Bids/scripts/dcm2bids", line 88, in main
    app = Dcm2bids(**vars(args))
  File "/home/egarza/MRI/apps/Dcm2Bids/dcm2bids/dcm2bids.py", line 29, in __init__
    self.dicomdir = os.path.join(outputdir,'tmp_dcm2bids')
  File "/usr/local/bin/miniconda/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

```

**Comment by jooh** [comment]
Hi, I turned on issues on my fork, so please post issues with my version there instead:

https://github.com/jooh/Dcm2Bids/issues

If this particular problem is still an issue, can you also include a) the exact command you are using to call dcm2bids, b) your config JSON?

**Comment by cbedetti** [comment]
Thank jooh
