### ISSUE TITLE
Error running dcm2bids

### ISSUE THREAD

**Issue by zeydabadi** [cbedetti/Dcm2Bids#11]
Hi,
I followed the instruction for downloading and adding to the PATH. 
After running the dcm2bids I receive this error:

[zeydabadi@node3 mz]$ dcm2bids
Traceback (most recent call last):
  File "/home/zeydabadi/mz/Dcm2Bids/scripts/dcm2bids", line 7, in <module>
    from dcm2bids.dcm2bids import Dcm2bids
  File "/home/zeydabadi/mz/Dcm2Bids/dcm2bids/dcm2bids.py", line 7, in <module>
    from .sidecarparser import Sidecarparser
  File "/home/zeydabadi/mz/Dcm2Bids/dcm2bids/sidecarparser.py", line 7, in <module>
    from future.utils import iteritems
ImportError: No module named future.utils

Will you please help me to fix it?
Thanks!
Mahmoud

**Comment by neurolabusc** [comment]
I think you need to install the future library:
`pip install future`

**Comment by zeydabadi** [comment]
Didn't help much:

Traceback (most recent call last):
  File "/home/dti/Dcm2Bids/scripts/dcm2bids", line 7, in <module>
    from dcm2bids.dcm2bids import Dcm2bids
ImportError: No module named dcm2bids.dcm2bids

**Comment by cbedetti** [comment]
There is a new installation method, see the README.
It should resolve your issue.
