### ISSUE TITLE
Issue with dcm2bids_helper

### ISSUE THREAD

**Issue by dlevitas** [cbedetti/Dcm2Bids#19]
Hello,

I tried building a configuration file; however, I received the following error:
```
No handlers could be found for logger "dcm2bids"
Example in:
/Users/username/anaconda/bin/tmp_dcm2bids/helper
```

I checked this helper directory, but it was empty. 

I installed dcm2bids a few days ago using the following commands:
```
git clone https://github.com/cbedetti/Dcm2Bids.git
cd Dcm2Bids
pip install .
```

My python version is Python 2.7.13, and I am using MacOS Sierra 10.12.6

Is there something else I need to do in order to produce the configuration file?

**Comment by cbedetti** [comment]
I don't have access to a Mac, so I can't test it directly.
It should be fixed in the last version.

```
$ pip freeze | grep dcm2bids
dcm2bids==1.1.8
```
Do you have the last version ?

**Comment by dlevitas** [comment]
I actually gave up with the Mac version, and switched to a Linux cluster environment.  I tried the installation again, but received the following permissions error:
```
Exception:
Traceback (most recent call last):
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/N/soft/rhel6/python/2.7.3/lib/python2.7/site-packages/winreg'
```

Since I don't have admin privileges, is there a work-around I can use in this case?

**Comment by cbedetti** [comment]
Without admin privileges, you can use -e, --user or --prefix.
`pip install --help` to see what's the best fit for your need.
One example: `pip install --user dcm2bids`

**Comment by dlevitas** [comment]
Okay, I installed dcm2bid with
```
pip install --prefix $HOME/Dcm2Bids dcm2bids
```
I then tried running the dcm2bids_helper file using this command:
```
$HOME/Dcm2Bids/bin/dcm2bids_helper -d DICOMdir -o $HOME
```

but got this error:
```
Traceback (most recent call last):
  File "/N/u/dlevitas/Karst/Dcm2Bids/bin/dcm2bids_helper", line 8, in <module>
    from dcm2bids.dcm2niix import Dcm2niix
```

Do I need to update the python path to include the dcm2bids modules?

**Comment by dlevitas** [comment]
Actually, nevermind about that. I added it to my PATH, and now it's running. 

Thanks again.
