### ISSUE TITLE
CalledProcessError newest version

### ISSUE THREAD

**Issue by sportnoah14** [cbedetti/Dcm2Bids#54]
Hi, I just tried the newest version of dcm2bids and I occasionally get the following error

```
Error: Photometric Interpretation 'PALETTE COLOR' not supported
Traceback (most recent call last):
  File "/home/stephan/miniconda2/envs/dcm2bids/bin/dcm2bids", line 114, in <module>
    sys.exit(main())
  File "/home/stephan/miniconda2/envs/dcm2bids/bin/dcm2bids", line 110, in main
    return app.run()
  File "/home/stephan/miniconda2/envs/dcm2bids/lib/python3.7/site-packages/dcm2bids/dcm2bids.py", line 103, in run
    dcm2niix.run(self.forceDcm2niix)
  File "/home/stephan/miniconda2/envs/dcm2bids/lib/python3.7/site-packages/dcm2bids/dcm2niix.py", line 91, in run
    self.execute()
  File "/home/stephan/miniconda2/envs/dcm2bids/lib/python3.7/site-packages/dcm2bids/dcm2niix.py", line 104, in execute
    output = run_shell_command(cmd)
  File "/home/stephan/miniconda2/envs/dcm2bids/lib/python3.7/site-packages/dcm2bids/utils.py", line 109, in run_shell_command
    return check_output(shlex.split(commandLine))
  File "/home/stephan/miniconda2/envs/dcm2bids/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/stephan/miniconda2/envs/dcm2bids/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dcm2niix', '-b', 'y', '-ba', 'y', '-z', 'y', '-i', 'y', '-f', '%3s_%p_%z_%t', '-o', '/media/stephan/data_big/bids_data/tmp_dcm2bids/sub-NS143_ses-preimplant01', '/media/stephan/data_big/bids_data/sourcedata/sub-NS143/ses-preimplant01/MR']' returned non-zero exit status 1.
```

The dicoms get converted into niftis and stored in the tmp directory but then don't get renamed or any further processing. I've tried reinstalling a few times already. Any ideas what may be causing this? Thank you again for this app

**Comment by neurolabusc** [comment]
I have added a patch to the development version that should fix this issue:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix
mkdir build && cd build
cmake ..
make
```

In the past, an error was generated, and I believe this terminates Dcm2Bids
`printError("Photometric Interpretation 'PALETTE COLOR' not supported\n");`
the new version should simply generate a warning and skip these images:
`printWarning("Photometric Interpretation 'PALETTE COLOR' not supported\n");`
Palette colors are always low precision, and do not have a direct equivalent in NIfTI. One could convert these to RGB images which do exist in NIfTI, but few NIfTI tools handle these and the precision remains low. In my experience, palette colors are only used for derived images, and therefore you want to skip these files and convert the high-precision raw data (which should yield better derived values after processing).

In my experience, palette colors is exceptionally rare. You may want to work out the providence of these images and see if there is a way to store them in more common format.

**Comment by sportnoah14** [comment]
I think I resolved this. I think it was the dicoms (possibly the way they were retrieved, stored, downloaded, not sure). It now works. There are a lot of derivatives that are included with the dicoms so I filter out using -i switch in dcm2niix. Thanks for all the help
