### ISSUE TITLE
Impossible to run dcm2bids on shared folder between vbox Linux and host Windows

### ISSUE THREAD

**Issue by mdurandruel** [cbedetti/Dcm2Bids#66]
Hello, 

I am running dcm2bids on a virtualbox Ubuntu with host windows. My data being on a hard disk, I mounted it as a shared folder in the guest virtual machine. When I try running dcm2bids_scaffold, dcm2bids_helper there are no problems. However, I get these messages when I try running dcm2bids:

Traceback (most recent call last):
  File "/home/manon/.local/bin/dcm2bids", line 114, in <module>
    sys.exit(main())
  File "/home/manon/.local/bin/dcm2bids", line 109, in main
    app = Dcm2bids(**vars(args))
  File "/home/manon/.local/lib/python2.7/site-packages/dcm2bids/dcm2bids.py", line 55, in __init__
    self.set_logger()
  File "/home/manon/.local/lib/python2.7/site-packages/dcm2bids/dcm2bids.py", line 94, in set_logger
    setup_logging(self.logLevel, logFile)
  File "/home/manon/.local/lib/python2.7/site-packages/dcm2bids/logger.py", line 21, in setup_logging
    handler = logging.FileHandler(logFile)
  File "/usr/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 71] Protocol error: '/home/manon/shared/Data_MRI/dcm2bids/tmp_dcm2bids/log/sub-ECSH6_ses-01_2019-09-10T15:30:19.944681.log'

Has anyone seen this already? and do you think there is a way to fix this problem?

Thanks and best

**Comment by cbedetti** [comment]
Thank you for reporting this issue.
It's fix with 3e69ea0c609bc00ff120d9438879ee1fd1e933b7 and will be available in the next release.
