### ISSUE TITLE
Logfile format incompatible with Windows (use of ':' prohibited)

### ISSUE THREAD

**Issue by LeoCeravolo** [cbedetti/Dcm2Bids#73]
Hi,

first of all, thanks for this great tool !

I am having an issue running dcm2bids on Ubuntu (18.04; Python 3.8, dcm2bids 2.1.4) on a Windows 10 pc. The specific issue is that after the helper step (which works perfectly), when running dcm2bids the first thing it does is (trying to) write a logfile if I understood correctly. The format is compatible with linux but not windows for a filename, therefore causing the following error:

Traceback (most recent call last):
  File "/home/leonardoceravolo/.local/bin/dcm2bids", line 114, in <module>
    sys.exit(main())
  File "/home/leonardoceravolo/.local/bin/dcm2bids", line 109, in main
    app = Dcm2bids(**vars(args))
  File "/home/leonardoceravolo/.local/lib/python2.7/site-packages/dcm2bids/dcm2bids.py", line 55, in __init__
    self.set_logger()
  File "/home/leonardoceravolo/.local/lib/python2.7/site-packages/dcm2bids/dcm2bids.py", line 94, in set_logger
    setup_logging(self.logLevel, logFile)
  File "/home/leonardoceravolo/.local/lib/python2.7/site-packages/dcm2bids/logger.py", line 21, in setup_logging
    handler = logging.FileHandler(logFile)
  File "/usr/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 22] **invalid mode ('a') or filename**: '/mnt/g/LALIDE/LALIDE1_fMRI/tmp_dcm2bids/log/sub-ID01_2019-11-07T11:49:34.777539.log'

Similar issue was raised [here](https://github.com/scrapinghub/scrapyrt/pull/44) for scrapyrt.

How should I proceed to replace ':' in the log filename by for instance '-' ?

thanks for your help!
Best,
Leo

**Comment by LeoCeravolo** [comment]
Hi again,

I moved my data to a Linux server and it all worked well on there, but it still may be a cool feature to have it compatible with windows at it seems to be just a simple file saving format issue.

Thanks again for this great tool!

best,
Leo

**Comment by cbedetti** [comment]
Thank you for reporting this issue.
It's fix with 3e69ea0c609bc00ff120d9438879ee1fd1e933b7 and will be available in the next release.
